# Copyright 2016, 2017 Peter Dimov
# Copyright 2017 Kohei Takahashi
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false

dist: precise

env:
  global:
    - PROJECT=libs/fusion

matrix:
  include:
    - os: linux
      env: TOOLSET=clang-3.0 CXXSTD=03,11
      addons:
        apt:
          packages:
            - clang-3.0

    - os: linux
      env: TOOLSET=clang-3.1 CXXSTD=03,11
      addons:
        apt:
          packages:
            - clang-3.1

install:
  # Sadly git's --shallow-submodules has hardcoded depth of 1 commit
  # Patch the git binary with a little more depth to deal with boost-commitbot's lag
  - sed 's/--depth=1/--depth=9/g' `which git` > ~/git && chmod +x ~/git

  # Checkout Boost
  - ~/git clone -j10 --branch=$BRANCH --depth=1 --quiet
      --recurse-submodules=":(exclude)$PROJECT" --shallow-submodules
      https://github.com/boostorg/boost.git $BOOST_ROOT
  - pushd $BOOST_ROOT
  # Remove the empty folder
  - rm -rf $PROJECT
  # Move the repository to boost/libs and make a link to previous place
  - mv $TRAVIS_BUILD_DIR $PROJECT
  - ln -s $PROJECT $TRAVIS_BUILD_DIR

  - ./bootstrap.sh
  - ./b2 headers

script:
  - ./b2 libs/fusion/test toolset=$TOOLSET cxxstd=$CXXSTD define=RUNNING_ON_TRAVIS=1
